version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.production
    ports:
      - 3000:3000
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: